# Sets the default theme when Home Assistant starts

alias: "default_theme"
initial_state: on
trigger:
  platform: homeassistant
  event: start
action:
  service: frontend.set_theme
  data:
    name: "darkred"
