# Sends a notification when a new version
# of Home Assistant for Hass.io is released.

alias: "hacs_update_notification"
trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: "off"
    to: "on"
action:
  - service: notify.kadse
    data_template:
      title: "*New Home Assistant Release*"
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is now available."