# Randomly changes the colors of my lamps

alias: "disco"
trigger:
  - platform: time_pattern
    seconds: "/1"
condition:
  - condition: state
    entity_id: input_boolean.party
    state: "on"
action:
  - service: light.turn_on
    entity_id:
    - light.jonas_lamp
    - light.spotlight0
    - light.3dprinter_backlight
    data_template:
      brightness: 100
      transition: 1
      rgb_color:
      - "{{ (range(0, 255)|random) }}"
      - "{{ (range(0, 50)|random) }}"
      - "{{ (range(0, 100)|random) }}"