# Turn on my growlight at 08:00 am 

alias: "turn_on_growlight"
trigger:
  - platform: time
    at: "08:00:00"
condition:
action:
  - service: switch.turn_on
    data:
      entity_id: switch.growlight
