# Activates the scene heaven at 6:00AM when I'm at home and it's a workday 

alias: "turn_on_lights_heaven"
trigger:
  - platform: time
    at: "06:00:00"
condition:
  - condition: state
    entity_id: person.kadse
    state: "home"
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
action:
  - service: scene.turn_on
    data:
      entity_id: scene.heaven
